#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

REV='ba1b5f0c23b3'
git2go_rel_dir='vendor/github.com/libgit2/git2go'

if [[ ! -e "${git2go_rel_dir}" ]]; then
  printf 'No git2go vendored dir: %s\n' "${git2go_rel_dir}"
  exit 1
fi

git2go_dir=$(readlink -f "${git2go_rel_dir}")

if [[ -e "${git2go_dir}"/static-build ]]; then
  printf 'Deleting existing static-build\n'
  rm -rf "${git2go_dir}"/static-build
fi

TMP=$(mktemp -d)
trap 'rm -rf $TMP' EXIT HUP TERM

pushd "${TMP}" >/dev/null
git clone https://github.com/libgit2/git2go

pushd git2go >/dev/null
git checkout "${REV}"
git submodule update --init
make build-libgit2
cp -r static-build "${git2go_dir}"/
popd >/dev/null
popd >/dev/null
