#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# found in git2go: git submodule
LIBGIT2_REV='6777db8e8343014d57c41b335e0c60af44d4e9f2'
BUILD_SCRIPT='build-libgit2-static.sh'

git2go_rel_dir='vendor/github.com/libgit2/git2go'

if [[ ! -e "${git2go_rel_dir}" ]]; then
  printf 'No git2go vendored dir: %s\n' "${git2go_rel_dir}"
  exit 1
fi

build_script_path="$PWD"/script/"${BUILD_SCRIPT}"
if [[ ! -e "${build_script_path}" ]]; then
  printf 'No libgit2 build script found: %s\n' "${build_script_path}"
  exit 1
fi

if [[ -e "${git2go_rel_dir}"/static-build ]]; then
  printf 'Static build already exists! %s\n' "${git2go_rel_dir}"/static-build
  exit 1
fi

pushd "${git2go_rel_dir}" >/dev/null

mkdir -p vendor
git clone https://github.com/libgit2/libgit2 vendor/libgit2

pushd vendor/libgit2 >/dev/null
git checkout "${LIBGIT2_REV}"
popd >/dev/null

mkdir -p script
cp "${build_script_path}" script/
./script/"${BUILD_SCRIPT}"

popd >/dev/null
