#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
shopt -s lastpipe

if [[ -v PUPPET_COMMIT ]] && [[ -n "${PUPPET_COMMIT}" ]]; then
  printf '%s\n' "${PUPPET_COMMIT}"
else
  exec git rev-parse HEAD
fi
