#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

AUTHORS=(
  [1]='lollipopman <hathaway@paypal.com>'
  [2]='lollipopman <hathaway@paypal.com>'
  [3]='lollipopman <hathaway@paypal.com>'
  [4]='lollipopman <hathaway@paypal.com>'
  [5]='lollipopman <hathaway@paypal.com>'
  [6]='lollipopman <hathaway@paypal.com>'
  [7]='lollipopman <hathaway@paypal.com>'
  [8]='lollipopman <hathaway@paypal.com>'
  [9]='lollipopman <hathaway@paypal.com>'
  [10]='lollipopman <hathaway@paypal.com>'
)

MSGS=(
  [1]='commit1'
  [2]='stop nginx on fozzie & add episode one

stop nginx on fozzie
add episode one
modify wit on statler
modify poignant on waldor
modify slapstick on fozzie'
  [3]='finish the muppet show lyrics

finish composing the muppet show lyrics
move index out of muppetshow class into node
class'
  [4]='New Movie'
  [5]='Gonzo'
  [6]='add some fun diversions

add bsdgames on fozzie
add sl to statler & waldorf
'
  [7]='add kermit user, modify sail input

add kermit user and muppetshow group
modify the input to the sail game
'
  [8]='More Statler'
  [9]='Even more Statler'
  [10]='add gonzo user'
)

REPO='muppetshow'

if [[ -e $REPO ]]; then
  sudo rm -fr "${REPO}"
fi
mkdir "${REPO}"

pushd "${REPO}"

git init
git config advice.detachedHead false

mkdir -p modules
cp -r ../manifests/vendor/* modules/
git add modules

MUPPET_SHOW_MOD='modules/muppetshow'
mkdir -p "${MUPPET_SHOW_MOD}"
mkdir -p "${MUPPET_SHOW_MOD}"/manifests

cp ../manifests/episode.pp "${MUPPET_SHOW_MOD}"/manifests/episode.pp
git add "${MUPPET_SHOW_MOD}"/manifests/episode.pp

cp ../puppet.conf ./
git add puppet.conf

for ((commit = 1; commit <= "${#AUTHORS[@]}"; commit++)); do
  if ((commit == 4)); then
    git checkout -b manhattan
  fi
  if ((commit == 6)); then
    git checkout master
  fi
  cp ../manifests/muppetshow"${commit}".pp "${MUPPET_SHOW_MOD}"/manifests/init.pp
  git add "${MUPPET_SHOW_MOD}"/manifests/init.pp
  cp ../manifests/nodes"${commit}".pp nodes.pp
  git add nodes.pp
  git commit --author "${AUTHORS[$commit]}" -F - <<<"${MSGS[commit]}"
  if ((commit == 1)); then
    git tag v1 -m 'Release v1'
  fi
  if ((commit == 7)); then
    git merge -m 'Take Manhattan' manhattan
    git tag v2 -m 'Release v2'
  fi
  if ((commit == 9)); then
    git tag v3 -m 'Release v3'
  fi
  if ((commit == 10)); then
    git tag v4 -m 'Release v4'
  fi
done

git remote add origin git@github.braintreeps.com:lollipopman/muppetshow.git
git push -fu origin master
git push -f --tags

popd
