#!/bin/bash
set -e errexit
set -e pipefail
set -o nounset

AUTHORS=(
  [1]='kermit <kermit@muppets.com>'
  [2]='fozzie <fozzie@muppets.com>'
  [3]='statler <statler@muppets.com>'
  [4]='statler <statler@muppets.com>'
  [5]='kermit <kermit@muppets.com>'
)

if [[ -e repo ]]; then
  sudo rm -fr repo
fi
mkdir repo

pushd repo

git init
git config advice.detachedHead false

mkdir -p modules
cp -r ../manifests/vendor/* modules/
git add modules

MUPPET_SHOW_MOD='modules/muppetshow'
mkdir -p "${MUPPET_SHOW_MOD}"
mkdir -p "${MUPPET_SHOW_MOD}"/manifests

cp ../manifests/episode.pp "${MUPPET_SHOW_MOD}"/manifests/episode.pp
git add "${MUPPET_SHOW_MOD}"/manifests/episode.pp

cp ../puppet.conf puppet.conf
git add puppet.conf

for ((commit = 1; commit <= "${#AUTHORS[@]}"; commit++)); do
  cp ../manifests/muppetshow"${commit}".pp "${MUPPET_SHOW_MOD}"/manifests/init.pp
  git add "${MUPPET_SHOW_MOD}"/manifests/init.pp
  cp ../manifests/nodes"${commit}".pp nodes.pp
  git add nodes.pp
  git commit --author "${AUTHORS[$commit]}" -m commit"${commit}"
done

popd
