#!/bin/bash

set -e nounset
set -e errexit
set -e pipefail
shopt -s lastpipe

if [[ $EUID -ne 0 ]]; then
  printf 'Must run as root!\n'
  exit 1
fi

export PATH=/opt/puppetlabs/bin:$PATH

pushd "${PWD}"/repo >/dev/null
git checkout master
git log --pretty=tformat:"%h" | tac | mapfile -t COMMITS
popd >/dev/null

MUPPETS=(
  waldorf
  statler
  fozzie
)

if [[ -e reports ]]; then
  rm -rf reports
fi

mkdir -p reports

FACTER_nodename='fozzie' FACTER_cwd="${PWD}" \
  puppet apply --confdir "${PWD}"/repo --vardir "${PWD}/var" manifests/reset.pp

for muppet in "${MUPPETS[@]}"; do
  mkdir -p reports/"${muppet}"
  for commit in "${COMMITS[@]}"; do
    pushd "${PWD}"/repo >/dev/null
    git checkout "${commit}" >/dev/null
    popd >/dev/null
    if [[ "$commit" == "${COMMITS[0]}" ]]; then
      FACTER_nodename="${muppet}" FACTER_cwd="${PWD}" \
        puppet apply --confdir "${PWD}"/repo --vardir "${PWD}/var" repo/nodes.pp
    fi
    report=reports/"${muppet}"/"${commit}"
    FACTER_nodename="${muppet}" FACTER_cwd="${PWD}" \
      puppet apply --noop --confdir "${PWD}"/repo --vardir "${PWD}/var" repo/nodes.pp >"${report}".txt 2>&1
    cp var/state/last_run_report.yaml "${report}".yaml
    chmod +r "${report}".yaml
    sed -i 's/^host: .*/host: '"${muppet}"'/' "${report}".yaml
  done
done

printf 'Set world read\n'
printf 'Done\n'
