// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hecklerpb.proto

package hecklerpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HecklerStatusRequest struct {
	Nodes []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (m *HecklerStatusRequest) Reset()         { *m = HecklerStatusRequest{} }
func (m *HecklerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*HecklerStatusRequest) ProtoMessage()    {}
func (*HecklerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd662ef9f4722, []int{0}
}
func (m *HecklerStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HecklerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HecklerStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HecklerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HecklerStatusRequest.Merge(m, src)
}
func (m *HecklerStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *HecklerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HecklerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HecklerStatusRequest proto.InternalMessageInfo

func (m *HecklerStatusRequest) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type HecklerStatusReport struct {
	NodeStatuses map[string]string `protobuf:"bytes,1,rep,name=node_statuses,json=nodeStatuses,proto3" json:"node_statuses,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *HecklerStatusReport) Reset()         { *m = HecklerStatusReport{} }
func (m *HecklerStatusReport) String() string { return proto.CompactTextString(m) }
func (*HecklerStatusReport) ProtoMessage()    {}
func (*HecklerStatusReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_993bd662ef9f4722, []int{1}
}
func (m *HecklerStatusReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HecklerStatusReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HecklerStatusReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HecklerStatusReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HecklerStatusReport.Merge(m, src)
}
func (m *HecklerStatusReport) XXX_Size() int {
	return m.Size()
}
func (m *HecklerStatusReport) XXX_DiscardUnknown() {
	xxx_messageInfo_HecklerStatusReport.DiscardUnknown(m)
}

var xxx_messageInfo_HecklerStatusReport proto.InternalMessageInfo

func (m *HecklerStatusReport) GetNodeStatuses() map[string]string {
	if m != nil {
		return m.NodeStatuses
	}
	return nil
}

func init() {
	proto.RegisterType((*HecklerStatusRequest)(nil), "hecklerpb.HecklerStatusRequest")
	proto.RegisterType((*HecklerStatusReport)(nil), "hecklerpb.HecklerStatusReport")
	proto.RegisterMapType((map[string]string)(nil), "hecklerpb.HecklerStatusReport.NodeStatusesEntry")
}

func init() { proto.RegisterFile("hecklerpb.proto", fileDescriptor_993bd662ef9f4722) }

var fileDescriptor_993bd662ef9f4722 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x48, 0x4d, 0xce,
	0xce, 0x49, 0x2d, 0x2a, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0xe9, 0x70, 0x89, 0x78, 0x40, 0x38, 0xc1, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x79, 0xf9, 0x29, 0xa9, 0xc5, 0x12, 0x8c, 0x0a, 0xcc,
	0x1a, 0x9c, 0x41, 0x10, 0x8e, 0xd2, 0x5a, 0x46, 0x2e, 0x61, 0x34, 0xe5, 0x05, 0xf9, 0x45, 0x25,
	0x42, 0xa1, 0x5c, 0xbc, 0x20, 0x05, 0xf1, 0xc5, 0x60, 0x41, 0xa8, 0x2e, 0x6e, 0x23, 0x03, 0x3d,
	0x84, 0xcd, 0x58, 0xb4, 0xe9, 0xf9, 0xe5, 0xa7, 0xa4, 0x06, 0x43, 0xb5, 0xb8, 0xe6, 0x95, 0x14,
	0x55, 0x06, 0xf1, 0xe4, 0x21, 0x09, 0x49, 0xd9, 0x73, 0x09, 0x62, 0x28, 0x11, 0x12, 0xe0, 0x62,
	0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x41, 0x6e, 0x2d, 0x4b,
	0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x46, 0xb1, 0x5c,
	0xec, 0x50, 0x7b, 0x85, 0x82, 0xb8, 0x78, 0x51, 0x9c, 0x20, 0x24, 0x8f, 0xdb, 0x71, 0xe0, 0x20,
	0x90, 0x92, 0xc3, 0xef, 0x7a, 0x25, 0x06, 0x27, 0x89, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92,
	0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c,
	0x96, 0x63, 0x48, 0x62, 0x03, 0x07, 0xb4, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x18, 0x6b, 0x96,
	0x90, 0x7b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HecklerClient is the client API for Heckler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HecklerClient interface {
	// applies a ref
	// rpc PuppetApply (PuppetApplyRequest) returns (PuppetReport) {}
	HecklerStatus(ctx context.Context, in *HecklerStatusRequest, opts ...grpc.CallOption) (*HecklerStatusReport, error)
}

type hecklerClient struct {
	cc *grpc.ClientConn
}

func NewHecklerClient(cc *grpc.ClientConn) HecklerClient {
	return &hecklerClient{cc}
}

func (c *hecklerClient) HecklerStatus(ctx context.Context, in *HecklerStatusRequest, opts ...grpc.CallOption) (*HecklerStatusReport, error) {
	out := new(HecklerStatusReport)
	err := c.cc.Invoke(ctx, "/hecklerpb.Heckler/HecklerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HecklerServer is the server API for Heckler service.
type HecklerServer interface {
	// applies a ref
	// rpc PuppetApply (PuppetApplyRequest) returns (PuppetReport) {}
	HecklerStatus(context.Context, *HecklerStatusRequest) (*HecklerStatusReport, error)
}

// UnimplementedHecklerServer can be embedded to have forward compatible implementations.
type UnimplementedHecklerServer struct {
}

func (*UnimplementedHecklerServer) HecklerStatus(ctx context.Context, req *HecklerStatusRequest) (*HecklerStatusReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HecklerStatus not implemented")
}

func RegisterHecklerServer(s *grpc.Server, srv HecklerServer) {
	s.RegisterService(&_Heckler_serviceDesc, srv)
}

func _Heckler_HecklerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HecklerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HecklerServer).HecklerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hecklerpb.Heckler/HecklerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HecklerServer).HecklerStatus(ctx, req.(*HecklerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Heckler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hecklerpb.Heckler",
	HandlerType: (*HecklerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HecklerStatus",
			Handler:    _Heckler_HecklerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hecklerpb.proto",
}

func (m *HecklerStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HecklerStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HecklerStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nodes[iNdEx])
			copy(dAtA[i:], m.Nodes[iNdEx])
			i = encodeVarintHecklerpb(dAtA, i, uint64(len(m.Nodes[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *HecklerStatusReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HecklerStatusReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HecklerStatusReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NodeStatuses) > 0 {
		for k := range m.NodeStatuses {
			v := m.NodeStatuses[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintHecklerpb(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintHecklerpb(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintHecklerpb(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintHecklerpb(dAtA []byte, offset int, v uint64) int {
	offset -= sovHecklerpb(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HecklerStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, s := range m.Nodes {
			l = len(s)
			n += 1 + l + sovHecklerpb(uint64(l))
		}
	}
	return n
}

func (m *HecklerStatusReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NodeStatuses) > 0 {
		for k, v := range m.NodeStatuses {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovHecklerpb(uint64(len(k))) + 1 + len(v) + sovHecklerpb(uint64(len(v)))
			n += mapEntrySize + 1 + sovHecklerpb(uint64(mapEntrySize))
		}
	}
	return n
}

func sovHecklerpb(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHecklerpb(x uint64) (n int) {
	return sovHecklerpb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HecklerStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHecklerpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HecklerStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HecklerStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHecklerpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHecklerpb
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHecklerpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HecklerStatusReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHecklerpb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HecklerStatusReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HecklerStatusReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeStatuses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHecklerpb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHecklerpb
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NodeStatuses == nil {
				m.NodeStatuses = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowHecklerpb
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowHecklerpb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthHecklerpb
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthHecklerpb
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowHecklerpb
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthHecklerpb
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthHecklerpb
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipHecklerpb(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthHecklerpb
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.NodeStatuses[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHecklerpb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHecklerpb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHecklerpb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHecklerpb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHecklerpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHecklerpb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHecklerpb
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHecklerpb
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHecklerpb
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHecklerpb        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHecklerpb          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHecklerpb = fmt.Errorf("proto: unexpected end of group")
)
